# permissions for end users to edit githubcomments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubcomment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: template-controller
    app.kubernetes.io/part-of: template-controller
    app.kubernetes.io/managed-by: kustomize
  name: githubcomment-editor-role
rules:
- apiGroups:
  - templates.kluctl.io
  resources:
  - githubcomments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.kluctl.io
  resources:
  - githubcomments/status
  verbs:
  - get
