apiVersion: templates.kluctl.io/v1alpha1
kind: TextTemplate
metadata:
  labels:
    app.kubernetes.io/name: texttemplate
    app.kubernetes.io/instance: texttemplate-sample
    app.kubernetes.io/part-of: template-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: template-controller
  name: texttemplate-sample
spec:
  # TODO(user): Add fields here
