apiVersion: v2
name: template-controller
maintainers:
  - name: kluctl
    url: https://github.com/kluctl
  - email: aljoscha.poertner@posteo.de
    name: AljoschaP
  - email: ablock84@gmail.com
    name: codablock
description: A Helm chart for the template-controller
type: application
version: "0.9.3"
appVersion: "v0.9.3"
