apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: http-prom
      protocol: TCP
      name: http-prom
    - port: {{ .Values.service.health.port }}
      targetPort: healthz
      protocol: TCP
      name: healthz
  selector:
    {{- include "template-controller.selectorLabels" . | nindent 4 }}
